apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: peerprep
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: asia-southeast1-docker.pkg.dev/peerprep-userservice-436407/peerprep/miljyy/user-service:latest
          ports:
            - name: user-service
              containerPort: 3001
          volumeMounts:
            - name: google-key
              mountPath: /backend/user-backend/googleKey.json
              subPath: googleKey.json
          env:
            - name: PORT
              value: "3001"
            - name: NODE_ENV
              value: production
            - name: ENV
              value: "PROD"
            - name: IMAGE_PROJECT_ID
              value: "peerprep-userservice-436407"
            - name: IMAGE_BUCKET
              value: "peerprep_userimages"
            - name: USER_AUTH_URL
              value: http://user-service:3001/auth/verify-token
            # create a secret named user-service-secret in namespace peerprep
            # kubectl create secret generic user-service-secret --from-literal=DB_CLOUD_URI=<mongo_url> --from-literal=JWT_SECRET=<jwt_secret>
            - name: DB_CLOUD_URI
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: DB_CLOUD_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: JWT_SECRET

            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /backend/user-backend/googleKey.json

      imagePullSecrets:
        - name: gcr-json-key

      volumes: # defines a volume named google-key to hold secrets
      # create a secret named google-key in namespace peerprep
      # kubectl create secret generic google-key --from-file=backend\user-backend\googleKey.json -n peerprep
        - name: google-key
          secret:
            secretName: google-key