apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: peerprep
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: user-service
      port: 3001
      targetPort: 3001
  type: ClusterIP # or LoadBalancer if using API Gateway