apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: peerprep
spec:
  ingressClassName: nginx
  rules:
    - host: 35.240.237.167.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 3001
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 3001
          - path: /api/questions
            pathType: Prefix
            backend:
              service:
                name: question-service
                port:
                  number: 4000
                  number: 3001
