# Specify the version of the Docker Compose.
version: "3.9"

# Define the services and applications that make up your application.
services:
  question-service:
    build: ./backend/question-backend
    ports:
      - 4000:4000
    volumes:
      - ./backend/question-backend:/app
      - /app/node_modules
    networks:
      - common-network

networks:
  common-network:
    driver: bridge