services:
  frontend-service:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - USER_AUTH_URL=http://user-service:3001/auth/verify-token
    networks:
      - common-network

  question-service:
    build: ./backend/question-backend
    ports:
      - 4000:4000
    volumes:
      - ./backend/question-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - USER_AUTH_URL=http://user-service:3001/auth/verify-token
    networks:
      - common-network

  user-service:
    build:
      context: ./backend/user-backend
    ports:
      - 3001:3001
    volumes:
      - ./backend/user-backend:/app
      - ./backend/user-backend/googleKey.json:/app/googleKey.json
      - /app/node_modules
    env_file:
      - ./backend/user-backend/.env
    networks:
      - common-network

networks:
  common-network:
    driver: bridge