apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: peerprep
  labels:
    app: history-service
spec:
  selector:
    app: history-service
  ports:
    - name: history-service
      port: 3004
      targetPort: 3004
  type: ClusterIP # or LoadBalancer if using API Gateway