apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  namespace: peerprep
  labels:
    app: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
        - name: matching-service
          image: matching-service # replace with your image
          ports:
            - containerPort: 3002
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
          readinessProbe: # Ensures that matching-service is only marked as ready when it is accessible
            httpGet:
              path: /health  # Update this path based on your service's health check endpoint
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
