apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: peerprep
  labels:
    app: matching-service
spec:
  selector:
    app: matching-service
  ports:
    - name: matching-service
      port: 3002
      targetPort: 3002
  type: ClusterIP # or LoadBalancer if using API Gateway