apiVersion: v1
kind: Service
metadata:
  name: collab-service
  namespace: peerprep
  labels:
    app: collab-service
spec:
  selector:
    app: collab-service
  ports:
    - name: collab-service-8200
      port: 8200
      targetPort: 8200
    - name: collab-service-8201
      port: 8201
      targetPort: 8201
  type: ClusterIP